name: Tests and security scans for Rust repos
description: Tests and security scans for Rust repos

inputs:
  WORKING_DIRECTORY:
    required: true
    default: "./libraries/rust/common-lib"
    description: 'The working directory in which the Cargo.toml resides.'


runs:
  using: composite
  steps:
  - name: Install Rust
    shell: bash
    run: |
      sudo apt-get install -y curl build-essential
      sudo curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - name: Test
    shell: bash
    run: |
      if [ -e "secrets.cfg" ]; then
          cat secrets.cfg
          source secrets.cfg
          echo "Environment variables sourced from secrets.cfg"
      else
          echo "File not found: secrets.cfg"
      fi
      RUST_LOG=debug cargo test
    working-directory: ${{ inputs.WORKING_DIRECTORY }}
  - name: Security scan 🔍/🛡️
    shell: bash
    run: |
      cargo install cargo-audit
      cargo audit
    working-directory: ${{ inputs.WORKING_DIRECTORY }}