name: Tests and vulnerability scans Rust library repos
description: Tests and vulnerability scans Rust library repos

inputs:
  WORKING_DIRECTORY:
    required: true
    default: "./libraries/rust/common-lib"
    description: 'The working directory in which the Cargo.toml resides.'


runs:
  using: composite
  steps:
  - name: Install Rust
    shell: bash
    run: |
      sudo apt-get install -y curl build-essential
      sudo curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - name: Run tests
    shell: bash
    run: |
      if [ -e "secrets.cfg" ]; then
          cat secrets.cfg
          source secrets.cfg
          echo "Environment variables sourced from secrets.cfg"
      else
          echo "File not found: secrets.cfg"
      fi
      cargo test
    working-directory: ${{ inputs.WORKING_DIRECTORY }}
  - name: Run cargo-audit to check for vulnerabilities in the source code 🔍/🛡️
    shell: bash
    run: |
      cargo install cargo-audit
      cargo audit
    working-directory: ${{ inputs.WORKING_DIRECTORY }}