name: Run C# tests
description: Run C# tests

inputs:
  TEST_WORKING_DIRECTORY:
    required: true
    default: "./libraries/c#/test"
    description: 'The test working directory in which the code resides.'


runs:
  using: composite
  steps:
  
  - name: Setup dotnet
    uses: actions/setup-dotnet@v3
    with:
      dotnet-version: '8.0.x'

  - name: Test
    shell: bash
    run: |
      echo "C# test results" | tee -a $GITHUB_STEP_SUMMARY
      find . -type f -name "*.csproj" -exec dotnet build {} \; > /dev/null
      find . -type f -name "*.csproj" -exec dotnet test {} \; | tee >(grep -E 'Failed:|Passed:|Skipped:' | tee -a $GITHUB_STEP_SUMMARY)
    working-directory: ${{ inputs.TEST_WORKING_DIRECTORY }}